const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('public/ciudad-viva/index.html','utf8');
const nodes=new Map();
function node(){return{focus(){},scrollIntoView(){},click(){this.listeners?.click?.({target:this})},style:{setProperty(){}},closest(){return this},contains(){return false},dataset:{},children:[],textContent:'',innerHTML:'',classList:{add(){},remove(){},toggle(){},contains(){return false}},addEventListener(type,fn){(this.listeners??={})[type]=fn},prepend(x){this.children.unshift(x);if(this.children.length>14)this.children.pop()},appendChild(x){this.children.push(x)},remove(){},setAttribute(){},getBoundingClientRect(){return{left:0,top:0,width:1100,height:720}},offsetWidth:330,offsetHeight:320,clientWidth:1100,clientHeight:720,setPointerCapture(){}};}
const gl=new Proxy({getShaderParameter(){return true},getProgramParameter(){return true},getAttribLocation(){return 0},getUniformLocation(){return{}},getShaderInfoLog(){return''},getProgramInfoLog(){return''}}, {get:(o,k)=>o[k]||(()=>({}))});
const doc={body:node(),querySelector(sel){if(!nodes.has(sel))nodes.set(sel,node());return nodes.get(sel)},querySelectorAll(){return[]},createElement:node,addEventListener(){}};
doc.querySelector('#glCanvas').getContext=()=>gl;
const ctx={document:doc,window:{addEventListener(){}},performance:{now:()=>1000},requestAnimationFrame(){},setTimeout(){},setInterval(){},fetch:()=>new Promise(()=>{}),AbortSignal,clearTimeout(){},devicePixelRatio:1,console,Math,Float32Array,Uint16Array};
vm.createContext(ctx);
let js=html.match(/<script>([\s\S]*?)<\/script>/)[1];
js=js.replace(/\}\)\(\);\s*$/, `Object.assign(thisTest,{renderResearchAndLoan,transitRoadRelief,buildingEmissions,operational,cityNews,upgradeToMaximum,roadConstructionQuote,advanceGuide,guideRequirementMet,presentNextNews,addEvent,currentUnlockAdvice,computeGoods,goodsDemand,goodsRequirement,goodsCanPlace,goodsFactor,industrialFusionGroup,roadComponents,computeTraffic,clearBuilding,isIndustry,getGoodsRoutes:()=>goodsRoutes,getTrafficRoutes:()=>trafficRoutes,captureProduction:buildings=>{captureParts=[];drawIndustryProduction(buildings);const p=captureParts;captureParts=null;return p;},parkFusionGroup,parkSections,localResidentialSatisfaction,roadLaneDividers,ROAD_LANES,roadLamp,FS,repayLoan,researchDemand,surfaceFor,parkLampOffsets,shortestRoadPath,laneOffset,tickSimulation,markActivity,getSpeed:()=>runningSpeed,fireProbability,debugAdvanceLevel,buildingPalette,crossfadeMusic,toggleAnalysis,setLayer,setFrame:n=>lastFrame=n,upgradeSpace,renderEmergency,windowLight,hasCrosswalk,roadColor,roadDragQuote,metricAvailable,layerValue,localServices,cityParticles,getServiceCars:()=>serviceCars,fusionGroup,mergeSelected,renameCity,rotatePlacement,generateRiver,buildingDef,buildingUpgradeCost,canPlace,currentSun,drawRoadTile,renderCityGuide,takeLoan,loanLimit,loanHourly,loanTerms,unlockTechnology,buildingLocked,buildPrice,taxDiscomfort,spreadFires,fireProtection,trafficSpeedFactor,simulationRate,serviceEfficiency,citySnapshot,restoreCity,setDebug,canAfford,changeMoney,ensureLevel,maxAllowedLevel,commercialRevenue,apportion,buildingStats,renderUI,buildRoadDrag,demolishSelected,getState:()=>S,setState:s=>S=s,newState,DEF,LEVELS,UP_MULT,idx,coord,footprint,build,calc,advance,uniqueBuildings,placementRotation,buildingCells,openPopup,moveSelected,placeMoved,cancelAction,showLandPopup,buySelectedLand,upgradeSelected,upgradeCost,drawBuilding,thumbSVG,power,STAR_FIELD,render3D,updateCars,getCars:()=>cars,setSpeed:n=>{runningSpeed=n;if(n)markActivity(lastFrame)},resetCars:()=>cars=[],captureRoad:(i)=>{captureParts=[];const c=coord(i),w=worldFromCell(c.x,c.z);drawRoadTile(i,S.grid[i],w);const p=captureParts;captureParts=null;return p;},geometryFor,smogAmount,capture:b=>{captureParts=[];const fp=b.parkLevels?{w:b.w,h:b.h}:footprint(b.type,b.rot||0,b.level);drawBuilding({...b,w:fp.w,h:fp.h,anchor:0},-(fp.w-1)/2,-(fp.h-1)/2);const p=captureParts;captureParts=null;return p;}});})();`);
js=js.replace('Object.assign(thisTest,{','Object.assign(thisTest,{serviceContribution,serviceDelta,attractiveness,influenceRadius,maximumUpgradeCost,utilityStatus,statLabel,lightIndustrialFusionGroup,ironicHeadlines,nameNewCity,vertexDataForParts,closePopup,updatePopupPosition,renderPalette,buildingSpecs,captureLayer:b=>{captureParts=[];captureScene=true;const fp=footprint(b.type,b.rot||0,b.level);drawBuilding({...b,w:fp.w,h:fp.h,anchor:0},-(fp.w-1)/2,-(fp.h-1)/2);const p=captureParts;captureParts=null;captureScene=false;return p;},captureLayerRoad:i=>{captureParts=[];captureScene=true;const c=coord(i);drawRoadTile(i,S.grid[i],worldFromCell(c.x,c.z));const p=captureParts;captureParts=null;captureScene=false;return p;},');
ctx.thisTest={};vm.runInContext(js,ctx);const g=ctx.thisTest;
function reset(){g.setState(g.newState());const s=g.getState();s.landUnlocked.fill(true);s.river.fill(false);s.money=1e8;s.cityLevel=8;s.day=100;s.unlockAt=Object.fromEntries(Object.keys(g.DEF).map(t=>[t,0]));s.technologies=['solar','wastewater','university','hospital','nuclear'];return s;}
function add(x,z,t,l=1,occ=0){const s=g.getState(),i=g.idx(x,z);if(['solar','wastewater','university','hospital','nuclear'].includes(t))s.researchCap=(s.researchUse||0)+10;g.build(i,t);const b=s.grid[i];assert(b&&b.type===t,`build ${t} ${x},${z}`);b.level=l;b.occ=occ;return b;}
const results=[];function test(n,f){f();results.push(n);console.log('PASS',n)}

test('Solar starts at N3 and gains one upgrade at each city level',()=>{
 const s=reset();for(let city=4;city<=8;city++){s.cityLevel=city;assert.equal(g.maxAllowedLevel('solar'),city<5?0:city-2);}assert.equal(g.DEF.solar.max,6);assert(g.DEF.solar.powerCap[6]>g.DEF.solar.powerCap[5]);
});

test('New cities have 15000 and a clear 6 by 6 starting area; existing balances survive loading',()=>{
 for(let n=0;n<24;n++){const s=g.newState();assert.equal(s.money,15000);const cells=s.landUnlocked.flatMap((v,i)=>v?[i]:[]);assert.equal(cells.length,36);assert.equal(new Set(cells.map(i=>g.coord(i).x)).size,6);assert.equal(new Set(cells.map(i=>g.coord(i).z)).size,6);assert(cells.every(i=>!s.river[i]));}
 const s=reset();s.money=1234;g.restoreCity(JSON.parse(JSON.stringify(g.citySnapshot())));assert.equal(g.getState().money,1234);assert.equal(g.buildPrice('coal'),5000);
 for(let city=3;city<=6;city++){g.getState().cityLevel=city;assert.equal(g.maxAllowedLevel('recycling'),city-1);}
});
test('School, health, police and fire require the same road network; reconnecting restores coverage',()=>{
 for(const [type,kind] of [['school','education'],['clinic','health'],['police','security'],['fire','fire']]){
  reset();add(8,8,'road');const home=add(8,9,'residential',1,12),shop=add(7,8,'commercial');add(10,8,'road');const source=add(10,9,type);
  assert.equal(g.localServices([home],g.uniqueBuildings(),0,1,1)[kind],0,type);
  if(type==='fire')assert.equal(g.fireProtection(shop),0);
  add(9,8,'road');assert(g.localServices([home],g.uniqueBuildings(),0,1,1)[kind]>0,type);
  if(type==='fire')assert(g.fireProtection(shop)>0);
  assert.equal(g.influenceRadius({...source,level:3})-g.influenceRadius(source),1);
 }
});
test('Grace preserves real coverage and removes only negative service contributions',()=>{
 const s=reset();s.day=100;for(const type of ['school','clinic','police','fire'])s.unlockAt[type]=100;
 add(8,8,'road');const home=add(8,9,'residential',1,12),values=g.localServices([home],g.uniqueBuildings(),0,1,1);
 for(const kind of ['education','health','security','fire'])assert.equal(values[kind],0);
 assert.equal(g.serviceContribution(values),0);assert(g.serviceContribution({...values,health:100})>0);
 const cityBase=64,happiness=g.localResidentialSatisfaction(home,[home],cityBase);assert.equal(home.satisfactionBreakdown.services,0);assert.equal(home.satisfactionBreakdown.baseEnvironmentAndLimits,happiness);
 assert.equal(g.serviceDelta('health',0),0);s.day=125;assert(g.serviceContribution(values)<0);assert.equal(g.serviceDelta('health',0),-50);
});
test('Prison supplies global security with staffing and resources, but harms nearby homes',()=>{
 const s=reset();s.debug=true;add(8,8,'road');const home=add(8,9,'residential',1,100);add(12,8,'road');const prison=add(11,9,'prison');s.debug=false;
 prison.workers=g.DEF.prison.jobs[1];prison.goodsCoverage=1;
 assert(g.localServices([home],g.uniqueBuildings(),0,1,1).security>0);prison.workers=0;assert.equal(g.localServices([home],g.uniqueBuildings(),0,1,1).security,0);prison.workers=g.DEF.prison.jobs[1];
 assert.equal(g.influenceRadius(prison,'nuisance'),4);assert.equal(g.influenceRadius(prison),0);assert(g.DEF.prison.coverage[1]/4>g.DEF.police.coverage[1]);assert(g.goodsDemand('prison',1)>0);
 assert(g.localResidentialSatisfaction(home,[home,prison],64)<g.localResidentialSatisfaction(home,[home],64));
 for(const type of ['park','monument','hospital','university','transit','library']){const b={type,level:1};assert.equal(g.influenceRadius({...b,level:2})-g.influenceRadius(b),.5,type);}
});
test('Light factory pairs merge at city N5, keep production and survive both orientations',()=>{
 for(const vertical of [false,true]){
  const s=reset();s.debug=true;const a=add(8,8,'light_industry',2),b=add(vertical?8:9,vertical?9:8,'light_industry',2);s.debug=false;s.cityLevel=4;
  assert.equal(g.lightIndustrialFusionGroup(a.anchor),null);s.cityLevel=5;b.level=3;assert.equal(g.lightIndustrialFusionGroup(a.anchor),null);b.level=2;b.fire=1;assert.equal(g.lightIndustrialFusionGroup(a.anchor),null);b.fire=0;
  g.openPopup(a.anchor);assert(g.mergeSelected());const merged=s.grid[a.anchor];assert.equal(merged.type,'light_industrial_complex');assert.equal(merged.w,vertical?1:2);assert.equal(merged.h,vertical?2:1);
  for(const field of ['jobs','goods','power','water','upkeep'])assert.equal(g.DEF[merged.type][field][2],2*g.DEF.light_industry[field][2],field);
  g.restoreCity(JSON.parse(JSON.stringify(g.citySnapshot())));assert.equal(g.uniqueBuildings().filter(b=>b.type==='light_industrial_complex').length,1);
 }
});
test('Prison and light campus geometry stays inside every rotated footprint at all levels',()=>{
 for(const type of ['prison','light_industrial_complex'])for(let level=1;level<=g.DEF[type].max;level++)for(let rot=0;rot<4;rot++){
  const fp=g.footprint(type,rot,level),parts=g.capture({type,level,rot,palette:0});assert(parts.length>20);
  for(const p of parts){const ex=Math.abs(Math.cos(p.ry))*p.sx/2+Math.abs(Math.sin(p.ry))*p.sz/2,ez=Math.abs(Math.sin(p.ry))*p.sx/2+Math.abs(Math.cos(p.ry))*p.sz/2;assert(Math.abs(p.x)+ex<=fp.w/2+.02,type+' x');assert(Math.abs(p.z)+ez<=fp.h/2+.02,type+' z');}
 }
});
test('Construction is ordered by city level, road toggles off, and max quote equals total payment',()=>{
 const s=reset();g.renderPalette();const palette=nodes.get('#palette'),last=palette.children.slice(palette.children.findLastIndex(n=>n.dataset.type==='road')),types=last.map(n=>n.dataset.type);
 for(let i=1;i<types.length;i++)assert(g.DEF[types[i]].unlock>=g.DEF[types[i-1]].unlock);
 const roads=palette.children.filter(n=>n.dataset.type==='road'),road=roads.at(-1);
 palette.listeners.click({target:{closest:()=>road}});assert.equal(s.tool,'road');palette.listeners.click({target:{closest:()=>road}});assert.equal(s.tool,'inspect');
 add(8,8,'road');const home=add(8,9,'residential');g.openPopup(home.anchor);const quoted=g.maximumUpgradeCost(home),before=s.money;assert(nodes.get('#upgradeMaxBtn').textContent.includes('Al máximo'));g.upgradeToMaximum();assert.equal(before-s.money,quoted);assert.equal(home.level,g.maxAllowedLevel(home.type));
});
test('Infrastructure statuses and building resource icons agree; goods has its own analysis layer',()=>{
 const s=reset();assert.match(g.utilityStatus(10,20),/Cobertura completa.*10/);assert.match(g.utilityStatus(20,10),/Déficit 10.*−10/);assert.match(g.utilityStatus(10,20,5),/Déficit 5/);
 for(const label of ['Consumo eléctrico','Agua','Mercancías','Investigación'])assert(g.statLabel(label).includes('<svg'),label);
 s.goodsCap=20;s.goodsUse=10;s.goodsDelivered=5;g.renderResearchAndLoan();assert.equal(nodes.get('#goodsBar').style.background,'var(--red)');
 assert(g.metricAvailable('goods'));g.setLayer('goods');assert.equal(s.layer,'goods');
 s.debug=true;add(8,8,'road');const factory=add(8,9,'light_industry');factory.goodsOutput=7;factory.industryEfficiency=.5;assert.equal(g.layerValue(factory,'goods'),50);assert(g.buildingStats(factory).some(([k,v])=>k==='Mercancías'&&String(v).includes('7')));
});
test('Tutorial cannot be skipped and requires water, data and inspection before completion',()=>{
 const s=reset();s.tutorialStep=3;g.renderCityGuide();assert.equal(g.advanceGuide(true),false);assert(!s.tutorialDone);assert(!g.guideRequirementMet());add(8,8,'road');const water=add(8,9,'water');g.advanceGuide();assert.equal(s.tutorialStep,4);g.toggleAnalysis('data');g.advanceGuide();assert.equal(s.tutorialStep,5);s.selected=null;assert(!g.guideRequirementMet());g.openPopup(water.anchor);g.advanceGuide();assert(s.tutorialDone);
});
test('Ticker stays active after exhausting history and uses news for existing buildings',()=>{
 const s=reset();s.newsSeen=Array.from({length:1024},(_,i)=>'Antigua '+i);const recent=[];
 for(let i=0;i<20;i++){g.presentNextNews();assert(s.newsActive);const log=nodes.get('#eventLog').children.at(-1);assert.equal(log.children.length,2);assert(log.children[0].textContent);recent.push(log.children[0].textContent);assert(s.newsSeen.length<=1024);}
 for(let i=1;i<recent.length;i++)assert.notEqual(recent[i],recent[i-1]);
 assert(!g.ironicHeadlines().some(t=>t.startsWith('Campus industrial')));s.debug=true;add(8,8,'light_industrial_complex');assert(g.ironicHeadlines().some(t=>t.startsWith('Campus industrial')));
});
(async()=>{
 const {validateCity}=await import('../server/city-api.mjs');
 test('Every client building maximum and rotated footprint is accepted by the server',()=>{
  reset();const base=JSON.parse(JSON.stringify(g.citySnapshot()));
  for(const [type,def] of Object.entries(g.DEF))for(let rot=0;rot<4;rot++){
   const fp=g.footprint(type,rot,def.max),building={type,level:def.max,anchor:g.idx(8,8),rot,w:fp.w,h:fp.h,occ:0,fire:0,palette:0,baseLevel:8};
   const save={...base,river:base.river.slice(),buildings:[building]};if(type==='wastewater')save.river[building.anchor-1]=true;
   const valid=validateCity(save);assert.equal(valid.buildings[0].level,def.max,type);assert.throws(()=>validateCity({...save,buildings:[{...building,level:def.max+1}]}),type);
   g.restoreCity(JSON.parse(JSON.stringify(valid)));assert.equal(g.uniqueBuildings()[0].type,type);assert.equal(g.uniqueBuildings()[0].cells.length,fp.w*fp.h,type);
  }
 });
 const s=reset();nodes.get('#cityAccess').hidden=true;const naming=g.nameNewCity();assert.equal(nodes.get('#cityNameScreen').hidden,false);assert(nodes.get('.app').inert);
 nodes.get('#newCityName').value='  Ciudad Serena  ';nodes.get('#cityNameForm').listeners.submit({preventDefault(){}});await naming;
 assert.equal(s.cityName,'Ciudad Serena');assert.equal(nodes.get('#cityNameScreen').hidden,true);assert.equal(nodes.get('.app').inert,false);console.log('PASS City naming uses a separate form and awaits completion');
})().catch(error=>{console.error(error);process.exitCode=1});

test('Research requirements do not lock selection but still prevent construction',()=>{
 const s=reset();s.researchCap=0;s.researchUse=0;g.renderPalette();const palette=nodes.get('#palette'),solar=palette.children.findLast(b=>b.dataset.type==='solar');assert(solar);assert(!solar.className.includes('locked'));assert(g.buildingSpecs('solar').includes('Energía solar'));
 palette.listeners.click({target:{closest:()=>solar}});assert.equal(s.tool,'solar');const money=s.money;g.build(g.idx(18,18),'solar');assert.equal(s.grid[g.idx(18,18)],null);assert.equal(s.money,money);
});
test('Urbanize toggles off with the same button',()=>{
 const s=reset(),button=nodes.get('#landBtn');button.listeners.click();assert.equal(s.tool,'land');button.listeners.click();assert.equal(s.tool,'inspect');
});
test('Transparent water uploads only top faces, without cell walls',()=>{
 reset();const part={x:0,y:0,z:0,sx:1,sy:.075,sz:1,col:'#3e8998',ry:0,em:0};const data=g.vertexDataForParts([part]);assert.equal(data.length,6*12);for(let i=0;i<data.length;i+=12){assert.equal(data[i+3],0);assert.equal(data[i+4],1);assert.equal(data[i+5],0);}assert(g.vertexDataForParts([{...part,col:'#758d91'}]).length>data.length);
});
test('Road lamps keep a stable random side, are smaller, and signals stay on intersections',()=>{
 const s=reset();for(let x=4;x<=26;x++)add(x,12,'road',5);const sides=new Set();for(let x=4;x<=26;x++){const i=g.idx(x,12),lamp=g.roadLamp(i,5),parts=g.captureRoad(i);assert(!parts.some(p=>p.col==='#263a43'));if(lamp){sides.add(lamp.side);assert.deepEqual(g.roadLamp(i,5),lamp);assert(parts.filter(p=>p.col==='#4e6b70').every(p=>p.sy<=.399));}}
 assert.equal(sides.size,2);add(14,11,'road',5);const parts=g.captureRoad(g.idx(14,12));assert.equal(parts.filter(p=>p.col==='#263a43').length,2);assert(parts.some(p=>p.col==='#e0d4b4'||p.col==='#eee8d3'));
});
test('All static model components and moving industrial goods respect map layers',()=>{
 const s=reset();for(const layer of ['pollution','economy','satisfaction','education','health','security','fire','traffic']){s.layer=layer;for(const type of ['heavy_industry','light_industry','coal','water','school','clinic','recycling','monument']){const parts=g.captureLayer({type,level:3,palette:0});assert.equal(new Set(parts.map(p=>p.col)).size,1,`${layer} ${type}`);assert(parts.every(p=>p.em===0));}}
 s.layer='none';const road=add(10,10,'road',5);add(9,10,'road',5);add(11,10,'road',5);add(10,9,'road',5);const factory=add(10,11,'heavy_industry');factory.industryEfficiency=1;s.layer='health';assert.equal(new Set(g.captureLayerRoad(road.anchor).map(p=>p.col)).size,1);assert(g.captureProduction([factory]).every(p=>p.col==='#596a70'&&p.em===0));s.layer='none';
});
test('Central Park upgrades add structures and service upgrades change geometry',()=>{
 reset();let previous=0;for(let level=5;level<=8;level++){const parts=g.capture({type:'park',level,parkLevels:[5,5],w:6,h:3});assert(parts.length>previous);previous=parts.length;}
 for(const type of ['school','clinic','coal','wastewater']){let previous='';for(let level=1;level<=g.DEF[type].max;level++){const parts=JSON.stringify(g.capture({type,level}));assert.notEqual(parts,previous);previous=parts;}}
});
test('Heavy smoke moves with rendering time, uses every chimney and is thinner than thermal smoke',()=>{
 const s=reset();s.debug=true;add(8,7,'road');const b=add(8,8,'heavy_industry',4);b.industryEfficiency=1;const smoke=g.cityParticles(0,[b]);assert.equal(smoke.length,14);assert.notDeepEqual(smoke,g.cityParticles(1,[b]));assert(smoke.every(p=>p.size<.22&&p.rgba[0]>.43&&p.rgba[0]<.58));
});
test('Building popup stays fixed through upgrades until closed',()=>{
 reset();add(8,7,'road');const b=add(8,8,'clinic'),popup=nodes.get('#buildingPopup'),original=popup.classList;let visible=false;popup.classList={add:()=>visible=true,remove:()=>visible=false,contains:()=>visible};g.openPopup(b.anchor);const position={...popup.style};assert(position.left&&position.top);g.upgradeSelected();popup.offsetHeight+=120;g.updatePopupPosition();assert.equal(popup.style.left,position.left);assert.equal(popup.style.top,position.top);g.closePopup();popup.offsetHeight-=120;popup.classList=original;
});

test('Cloud save round-trip preserves city data including enabled debug mode',()=>{const s=reset();add(8,8,'road');add(9,8,'road');add(10,8,'road');const park=add(8,9,'park',3);const home=add(10,9,'residential',4,65.7);s.day=200;s.money=43210;s.debug=true;s.unlockAt.school=42;const snapshot=g.citySnapshot();g.restoreCity(JSON.parse(JSON.stringify(snapshot)));const restored=g.getState();assert.equal(restored.money,43210);assert.equal(restored.day,200);assert.equal(restored.debug,true);assert.equal(restored.unlockAt.school,42);assert.equal(restored.grid[home.anchor].occ,65.7);assert.equal(restored.grid[park.anchor].level,3);assert.strictEqual(restored.grid[park.anchor],restored.grid[park.anchor+1]);assert.equal(g.uniqueBuildings().length,5);const normalized={...snapshot,debug:true};assert.deepEqual(JSON.parse(JSON.stringify(g.citySnapshot())),JSON.parse(JSON.stringify(normalized)));});
test('Final local services retain disease, crime and water penalties; fire coverage is zero without firefighters',()=>{
 const s=reset();for(let x=4;x<=12;x++)add(x,8,'road',5);const h=add(5,9,'residential',8,800);add(6,9,'clinic',3);add(7,9,'police',2);add(8,9,'water',4);const power=add(10,9,'coal',4);g.calc();const health=s.health,security=s.security;assert.equal(s.fireSafety,0);assert.equal(g.fireProtection(h),0);s.diseaseDays=10;s.crimeDays=10;g.calc();assert(Math.abs(s.health-(health-8))<.001);assert(Math.abs(s.security-(security-6))<.001);s.diseaseDays=s.crimeDays=0;const services=g.uniqueBuildings();const full=g.localServices([h],services,0,1,1).health,dry=g.localServices([h],services,0,1,0).health;assert(dry<full-20);s.grid[power.anchor]=null;g.calc();assert(g.localServices([h],g.uniqueBuildings(),0,.2,1).health<g.localServices([h],g.uniqueBuildings(),0,1,1).health);assert(s.waterCap<g.DEF.water.waterCap[4]);assert(g.uniqueBuildings().find(b=>b.type==='clinic').serviceEfficiency<1);
});
test('Crime lowers satisfaction in uncovered homes; demand is reflected directly in coverage',()=>{
 const s=reset();for(let x=4;x<10;x++)add(x,8,'road');const h=add(5,9,'residential',4,80);add(6,9,'water',3);add(7,9,'coal',3);g.calc();const baseline=h.localSatisfaction;s.crimeDays=10;g.calc();assert(h.localSatisfaction<baseline-9);s.crimeDays=0;add(9,9,'school');const all=g.uniqueBuildings();h.occ=100;const small=g.localServices([h],all,0).education;h.occ=700;const large=g.localServices([h],all,0).education;assert(large<small);assert.equal(Math.round(h.serviceCoverage.education*100),Math.round(large));
});
test('Fire spreads only to immediately adjacent buildings, with less spread under fire cover',()=>{
 const s=reset();for(let x=3;x<12;x++)add(x,8,'road');const source=add(4,9,'commercial'),near=add(5,9,'residential'),far=add(8,9,'commercial');source.fire=5;s.fireSafety=0;near.localServices={fire:0};assert.equal(g.spreadFires(1,()=>.02),1);assert(near.fire>0);assert.equal(far.fire,0);near.fire=0;near.localServices.fire=95;s.fireSafety=95;assert.equal(g.spreadFires(1,()=>.02),0);
});
test('Unused roads do not dilute weighted congestion; full congestion nearly stops cars',()=>{
 const s=reset();for(let x=4;x<13;x++)add(x,8,'road');add(4,9,'residential',7,400);add(12,9,'commercial',5);g.calc();g.calc();const original=s.avgTraffic;assert(original>0);for(let x=0;x<20;x++)add(x,0,'road');g.calc();assert(Math.abs(s.avgTraffic-original)<.0001);assert(g.trafficSpeedFactor(100)<.02);assert(g.trafficSpeedFactor(30)>.2);
});
test('Higher taxes reduce satisfaction convexly; construction and upgrades have fixed authored costs',()=>{
 const s=reset();s.cityLevel=1;const initial=g.buildPrice('residential'),upgrade=g.upgradeCost('commercial',1);s.cityLevel=8;assert.equal(g.buildPrice('residential'),initial);assert.equal(g.upgradeCost('commercial',1),upgrade);assert.equal(g.taxDiscomfort(10),0);assert(g.taxDiscomfort(20)-g.taxDiscomfort(15)>g.taxDiscomfort(15)-g.taxDiscomfort(10));s.cityLevel=1;add(8,8,'road');add(8,7,'water');add(8,9,'residential',1,18);s.tax=10;g.calc();const happy=s.happiness;s.tax=20;g.calc();assert(s.happiness<happy-30);
});
test('Emergency loan respects bankruptcy, term, city cap and single outstanding debt; installments amortize exactly',()=>{
 const s=reset();s.cityLevel=3;s.money=1;assert(!g.takeLoan(10000,1.5));s.money=0;assert(!g.takeLoan(g.loanLimit()+1,3));assert(!g.takeLoan(10000,4));assert(g.takeLoan(10000,1.5));assert(!g.takeLoan(10,3));const payment=g.loanHourly();assert.equal(s.money,10000);assert.equal(s.loan.total,10600);g.advance(1);assert(Math.abs(s.loan.remaining-(10600-payment))<.0001);assert(Math.abs(s.money-(10000-payment))<.0001);g.advance(1.5*30*24);assert.equal(s.loan,null);assert(Math.abs(s.money+600)<.0001);assert(g.loanTerms(10000,12).interest>g.loanTerms(10000,3).interest);
});
test('Research is fixed capacity, gates building, never accumulates and shortages reduce output',()=>{
 const s=reset();s.cityLevel=5;for(let x=4;x<14;x++)add(x,8,'road');add(4,9,'residential',8,500);add(9,9,'coal',3);add(7,9,'water',3);const lab=add(8,9,'research',3);g.calc();assert(s.researchCap>0);const cap=s.researchCap;g.advance(.1);assert.equal(s.researchPoints,0);assert(!g.buildingLocked('solar'));s.manualRotation=0;g.build(g.idx(12,9),'solar');const plant=s.grid[g.idx(12,9)];assert(plant);g.calc();assert(s.researchUse>0);g.openPopup(lab.anchor);g.demolishSelected();g.calc();assert.equal(s.researchCap,0);assert.equal(plant.researchEfficiency,0);assert(g.buildingLocked('solar'));s.researchPoints=10000;g.calc();assert.equal(s.researchPoints,0);assert(g.buildingLocked('solar'));
});
test('Normal time is capped at x3 and debug settings survive save/load',()=>{const s=reset();g.setSpeed(1);assert.equal(g.simulationRate(),.175);g.setSpeed(3);assert(Math.abs(g.simulationRate()-.525)<1e-10);const snapshot=g.citySnapshot();snapshot.debug=true;g.restoreCity(snapshot);assert.equal(g.getState().debug,true);g.setSpeed(0);});
test('Starter budget reaches the first promotion with only level-one unlocks',()=>{const s=g.newState();s.river.fill(false);g.setState(s);for(let x=16;x<=20;x++)add(x,18,'road');add(16,17,'water');add(17,17,'commercial');add(18,17,'commercial');for(const x of [16,17,18,19,20])add(x,19,'residential');assert(s.money>=0);for(let n=0;n<2000&&s.cityLevel<2;n++)g.advance(.25);assert(s.cityLevel>=2,`stalled ${s.pop}/${s.happiness}`);assert(s.money>0);});
test('Fusion of equal N4+ homes preserves capacity, occupancy and upkeep, upgrades and reloads as one unit',()=>{for(const level of [4,6,8]){const s=reset();for(let x=8;x<=11;x++){add(x,7,'road');add(x,10,'road');}const homes=[[9,8],[10,8],[9,9],[10,9]].map(([x,z])=>add(x,z,'residential',level,60));g.openPopup(homes[0].anchor);assert(g.fusionGroup());assert(g.mergeSelected());const b=s.grid[homes[0].anchor];assert.equal(b.type,'residential_block');assert.equal(b.level,level);assert.equal(b.occ,240);assert.equal(g.buildingDef(b).cap[level],g.DEF.residential.cap[level]*4);assert.equal(g.buildingDef(b).upkeep[level],g.DEF.residential.upkeep[level]*4);assert.equal(g.uniqueBuildings().filter(b=>b.type==='residential_block').length,1);g.upgradeSelected();assert.equal(b.level,Math.min(8,level+1));const saved=g.citySnapshot();g.restoreCity(JSON.parse(JSON.stringify(saved)));assert.equal(g.getState().grid[b.anchor].baseLevel,4);assert.equal(g.getState().grid[b.anchor].cells.length,4);}});
test('Fusion rejects mismatched levels and non-square groups',()=>{const s=reset();for(let x=8;x<13;x++)add(x,7,'road');const a=add(8,8,'residential',4);add(9,8,'residential',5);add(10,8,'residential',4);add(11,8,'residential',4);g.openPopup(a.anchor);assert.equal(g.fusionGroup(),null);assert(!g.mergeSelected());});
test('Park expansion is atomic, requires 3x3 land and preserves money and cells when blocked',()=>{const s=reset();add(8,7,'road');const park=add(8,8,'park',4);s.landUnlocked[g.idx(10,10)]=false;for(let z=7;z<=10;z++)s.landUnlocked[g.idx(7,z)]=false;g.openPopup(park.anchor);const cash=s.money;g.upgradeSelected();assert.equal(park.level,4);assert.equal(park.cells.length,4);assert.equal(s.money,cash);s.landUnlocked[g.idx(10,10)]=true;g.upgradeSelected();assert.equal(park.level,5);assert.equal(park.cells.length,9);assert(s.money<cash);assert.strictEqual(s.grid[g.idx(10,10)],park);});
test('Rectangular buildings rotate before placement; legacy compact buildings reload without overlap',()=>{for(const type of ['coal','hospital','nuclear','solar']){const s=reset();s.debug=true;add(8,7,'road');s.tool=type;s.manualRotation=0;g.rotatePlacement();assert.equal(s.manualRotation,1);const b=add(8,8,type);assert.equal(b.rot,1);assert.equal(b.cells.length,2);}const s=reset();const state=g.citySnapshot();state.format=1;state.buildings=[{type:'coal',level:1,anchor:200,rot:0,occ:0,palette:0,fire:0},{type:'commercial',level:1,anchor:201,rot:0,occ:0,palette:0,fire:0}];g.restoreCity(state);assert.equal(g.getState().grid[200].cells.length,1);assert.equal(g.getState().grid[201].type,'commercial');});
test('Every river is connected and crosses the map between two borders; bridges cost twice a road',()=>{for(let seed=0;seed<30;seed++){const river=g.generateRiver(seed);assert(river.some(Boolean));const cells=river.flatMap((v,i)=>v?[i]:[]),seen=new Set([cells[0]]),queue=[cells[0]];while(queue.length){const i=queue.pop(),x=i%36;for(const n of [i-36,i+36,...(x>0?[i-1]:[]),...(x<35?[i+1]:[])])if(n>=0&&n<1296&&river[n]&&!seen.has(n)){seen.add(n);queue.push(n);}}assert.equal(seen.size,cells.length);const borders=new Set(cells.flatMap(i=>{const x=i%36,z=Math.floor(i/36),a=[];if(x===0)a.push('left');if(x===35)a.push('right');if(z===0)a.push('top');if(z===35)a.push('bottom');return a;}));assert(borders.size>=2,`river borders ${seed}`);for(const i of cells){const x=i%36,z=Math.floor(i/36);assert([-1,0].some(dx=>[-1,0].some(dz=>{const a=x+dx,b=z+dz;return a>=0&&a<35&&b>=0&&b<35&&[0,1,36,37].every(d=>river[b*36+a+d]);})),`river width at ${seed}:${i}`);}}const s=reset();s.river[g.idx(8,8)]=true;const cash=s.money,b=add(8,8,'road');assert.equal(cash-s.money,g.buildPrice('road')*2);assert.equal(g.buildingUpgradeCost(b),g.upgradeCost('road',1)*2);});
test('Land purchase requires Urbanizar; rename costs 10000; fixed day and layers do not stop simulation',()=>{const s=reset();s.landUnlocked[0]=false;s.tool='inspect';g.showLandPopup(0);g.buySelectedLand();assert(!s.landUnlocked[0]);s.tool='land';g.showLandPopup(0);g.buySelectedLand();assert(s.landUnlocked[0]);const cash=s.money;assert(g.renameCity('Nueva Toledo'));assert.equal(s.money,cash-10000);s.day=0;s.dayNight=false;assert.equal(g.currentSun().hour,12);s.dayNight=true;s.layer='traffic';assert.equal(g.currentSun().hour,12);s.layer='none';assert.equal(g.currentSun().hour,0);const day=s.day;g.advance(.1);assert(s.day>day);});
test('New geometry and every rectangular rotation remain within their parcels',()=>{for(const type of ['residential_block','park','coal','hospital','nuclear','recycling','university','transit','research','wastewater','school','police','office'])for(const level of type==='residential_block'?[4,8]:type==='park'?[4,5]:[1,g.DEF[type].max])for(const rot of [0,1,2,3]){const fp=g.footprint(type,rot,level),parts=g.capture({type,level,rot,palette:0});for(const p of parts){const ex=Math.abs(Math.cos(p.ry))*p.sx/2+Math.abs(Math.sin(p.ry))*p.sz/2,ez=Math.abs(Math.sin(p.ry))*p.sx/2+Math.abs(Math.cos(p.ry))*p.sz/2;assert(Math.abs(p.x)+ex<=fp.w/2+.02,`${type} N${level} rot${rot} X`);assert(Math.abs(p.z)+ez<=fp.h/2+.02,`${type} N${level} rot${rot} Z`);}}});

test('Fusion requires all four homes at N4, including debug; old low-level fused saves remain compatible',()=>{const s=reset();s.cityLevel=4;for(let x=10;x<12;x++){add(x,9,'road');add(x,12,'road');}for(let x=10;x<12;x++)for(let z=10;z<12;z++)add(x,z,'residential',1,5);g.openPopup(g.idx(10,10));assert.equal(nodes.get('#mergeBtn').disabled,true);assert(!g.mergeSelected());s.debug=true;assert.equal(g.fusionGroup(),null);for(const b of g.uniqueBuildings())if(b.type==='residential')b.level=4;assert(g.mergeSelected());const snapshot=g.citySnapshot();snapshot.buildings.find(b=>b.type==='residential_block').baseLevel=1;g.restoreCity(snapshot);assert.equal(g.buildingDef(g.getState().grid[g.idx(10,10)]).cap[4],4*g.DEF.residential.cap[1]);});
test('Asphalt is above paving at all upgraded road levels; tower geometry is bounded and economical',()=>{const s=reset(),b=add(10,10,'road');for(let level=2;level<=8;level++){b.level=level;const parts=g.captureRoad(b.anchor),paving=parts.filter(p=>p.col==='#b4b7a9'),asphalt=parts.filter(p=>p.col===g.roadColor(0));assert(paving.length&&asphalt.length);assert(Math.min(...asphalt.map(p=>p.y+p.sy/2))>Math.max(...paving.map(p=>p.y+p.sy/2)));}assert(g.geometryFor('cooling').indices.length/3<=64);s.layer='none';s.pollution=10;assert.equal(g.smogAmount(),0);s.pollution=20;assert(g.smogAmount()>0);s.pollution=70;assert(g.smogAmount()>0);s.layer='traffic';assert.equal(g.smogAmount(),0);g.render3D();});

test('Park expands northwest when east and south are unavailable',()=>{const s=reset();add(9,10,'road');const b=add(8,8,'park',4);for(let z=7;z<=10;z++)s.landUnlocked[g.idx(10,z)]=false;for(let x=7;x<=10;x++)s.landUnlocked[g.idx(x,10)]=false;g.openPopup(b.anchor);g.upgradeSelected();assert.equal(b.level,5);assert.equal(b.anchor,g.idx(7,7));assert.equal(b.cells.length,9);assert.strictEqual(s.grid[g.idx(8,8)],b);});
test('Wastewater needs an orthogonal river neighbor for placement and relocation',()=>{const s=reset();add(8,7,'road');s.manualRotation=0;s.river[g.idx(9,10)]=true;assert(!g.canPlace(g.idx(8,8),'wastewater'));s.river[g.idx(9,9)]=true;const b=add(8,8,'wastewater');assert.equal(b.cells.length,2);add(12,7,'road');g.openPopup(b.anchor);g.moveSelected();g.placeMoved(g.idx(12,8));assert.equal(b.anchor,g.idx(8,8));s.river[g.idx(13,8)]=true;g.placeMoved(g.idx(12,8));assert.equal(b.anchor,g.idx(12,8));});
test('Old 30x24 cities migrate to 36x24 without changing coordinates or compact campus buildings',()=>{reset();const state=g.citySnapshot();state.format=2;state.width=30;state.height=24;state.landUnlocked=Array(720).fill(true);state.river=Array(720).fill(false);state.river[29]=true;state.buildings=[{type:'university',level:1,w:1,h:1,anchor:200,rot:0,occ:0,fire:0,palette:0}];g.restoreCity(state);const s=g.getState(),anchor=g.idx(20,6);assert.equal(s.grid.length,1296);assert.equal(s.grid[anchor].type,'university');assert.equal(s.grid[anchor].cells.length,1);assert(s.river[29]);assert(!s.landUnlocked[30]);assert.equal(g.citySnapshot().format,4);});
test('Bankruptcy immediately pauses, rejects insufficient rescue and preserves Game Over on reload',()=>{const s=reset();s.money=-501;g.setSpeed(1);g.renderEmergency();assert.equal(g.simulationRate(),0);assert.equal(nodes.get('#emergencyScreen').hidden,false);const day=s.day;g.advance(1);assert.equal(s.day,day);assert(!g.takeLoan(500,3));assert(g.takeLoan(1000,3));assert.equal(nodes.get('#emergencyScreen').hidden,true);s.money=-10;s.gameOver=true;const snapshot=g.citySnapshot();g.restoreCity(snapshot);assert(g.getState().gameOver);assert.equal(nodes.get('#restartCity').hidden,false);});
test('City promotion requires only population and the linear satisfaction target',()=>{const s=reset();s.pop=80;s.happiness=59;assert(!g.LEVELS[1].req(s));s.happiness=60;assert(g.LEVELS[1].req(s));s.pop=240;s.happiness=g.LEVELS[2].happiness;s.education=0;s.health=0;s.security=0;s.fireSafety=0;assert(g.LEVELS[2].req(s));s.happiness--;assert(!g.LEVELS[2].req(s));});
test('Weighted routing uses a reasonable parallel street when the direct route is loaded',()=>{const s=reset();for(let x=4;x<=9;x++){add(x,4,'road');add(x,6,'road');}add(4,5,'road');add(9,5,'road');const start=g.idx(4,4),end=g.idx(9,4);assert.equal(g.shortestRoadPath(start,new Set([end])).length,6);for(let x=5;x<9;x++)s.grid[g.idx(x,4)].trafficLoad=250;const alternate=g.shortestRoadPath(start,new Set([end]));assert(alternate.includes(g.idx(6,6)));assert(alternate.length<14);assert.equal(g.laneOffset({lane:0},4),g.laneOffset({lane:1},4));assert(g.laneOffset({lane:1},5)>g.laneOffset({lane:0},5));});
test('Elapsed time is preserved across hidden-tab delays, with normal and fast speed',()=>{const s=reset();g.setFrame(1000);g.setSpeed(1);const day=s.day;g.tickSimulation(61000);assert(Math.abs(s.day-day-60*.175)<1e-8);g.setSpeed(3);g.tickSimulation(63000);assert(Math.abs(s.day-day-62*.175-4*.175)<1e-8);g.setSpeed(0);const paused=s.day;g.tickSimulation(123000);assert.equal(s.day,paused);});
test('Simulation auto-pauses after exactly fifteen inactive minutes',()=>{const s=reset();g.setFrame(1000);g.setSpeed(1);const day=s.day;g.tickSimulation(1000+20*60*1000);assert.equal(g.getSpeed(),0);assert(Math.abs(s.day-day-15*60*.175)<1e-8);});
test('New maps are square and satisfaction requirements rise linearly from 60 to 85',()=>{const s=g.newState();g.setState(s);assert.equal(g.citySnapshot().width,g.citySnapshot().height);assert.equal(s.money,15000);const requirements=g.LEVELS.slice(1).map(l=>l.happiness);assert.equal(requirements[0],60);assert.equal(requirements.at(-1),85);for(let i=2;i<requirements.length;i++)assert(Math.abs((requirements[i]-requirements[i-1])-(requirements[i-1]-requirements[i-2]))<=1);assert(!g.debugAdvanceLevel());});
test('Music buffer has a blended wrap with bounded samples',()=>{const data=Float32Array.from({length:1000},(_,i)=>i/1000),buffer={sampleRate:100,length:1000,numberOfChannels:1,getChannelData:()=>data};let out;const ctx={createBuffer:(channels,length,rate)=>{out=new Float32Array(length);return {length,sampleRate:rate,getChannelData:()=>out};}};const loop=g.crossfadeMusic(ctx,buffer);assert.equal(loop.length,800);assert(Math.abs(out.at(-1)-out[0])<.01);assert(out.every(v=>v>=0&&v<=1));});
test('Layer exit restores normal view; fire risk respects grace and coverage',()=>{const s=reset();g.toggleAnalysis('layers');g.setLayer('traffic');g.toggleAnalysis('data');assert.equal(s.layer,'none');const b={type:'office',palette:2,anchor:400,rot:0};const pal=g.buildingPalette(b);b.rot=3;b.anchor=401;assert.strictEqual(g.buildingPalette(b),pal);s.cityLevel=5;s.day=10;s.unlockAt.fire=10;s.fireSafety=0;assert.equal(g.fireProbability(24),0);s.day=100;s.unlockAt.fire=0;const low=g.fireProbability(24);s.fireSafety=90;assert(low>g.fireProbability(24)*10);assert(low>.7);});
test('Police stations assign up to three cars according to building level',()=>{const s=reset();for(let x=4;x<14;x++)add(x,8,'road');const station=add(6,9,'police',1);g.updateCars(.01);assert.equal(g.getServiceCars().filter(c=>c.owner===station).length,1);station.level=3;g.updateCars(.01);assert.equal(g.getServiceCars().filter(c=>c.owner===station).length,2);station.level=5;g.updateCars(.01);assert.equal(g.getServiceCars().filter(c=>c.owner===station).length,3);});
test('N6–N8 parks and campus, reactor and transit upgrades have distinct geometry',()=>{reset();assert.equal(g.DEF.park.max,8);for(const type of ['park','university','nuclear','transit','research','wastewater']){let previous='';for(let level=type==='park'?5:1;level<=g.DEF[type].max;level++){const parts=JSON.stringify(g.capture({type,level,rot:0,palette:0}));assert.notEqual(parts,previous);previous=parts;}}});
test('Version 3 cities gain twelve locked rows while retaining buildings and river coordinates',()=>{reset();const old=g.citySnapshot();old.format=3;old.height=24;old.landUnlocked=Array(864).fill(true);old.river=Array(864).fill(false);old.river[100]=true;old.buildings=[{type:'commercial',level:1,w:1,h:1,anchor:200,rot:0,occ:0,fire:0,palette:0}];g.restoreCity(old);const s=g.getState();assert.equal(s.grid.length,1296);assert.equal(s.grid[200].type,'commercial');assert(s.river[100]);assert(s.landUnlocked.slice(864).every(v=>!v));});

test('Material responses and park lamp counts distinguish their surfaces and levels',()=>{assert(g.surfaceFor('#bedce0')[1]>g.surfaceFor('#d0dfcf')[1]);assert.equal(g.parkLampOffsets(4).length,2);assert.equal(g.parkLampOffsets(5).length,4);});

test('Compact wastewater saves preserve neighbors and expand safely on upgrade',()=>{const s=reset();add(8,7,'road');s.manualRotation=0;s.river[g.idx(9,9)]=true;const b=add(8,8,'wastewater');const saved=g.citySnapshot(),plant=saved.buildings.find(b=>b.type==='wastewater');plant.w=plant.h=1;g.restoreCity(saved);const restored=g.getState().grid[b.anchor];assert.equal(restored.cells.length,1);assert(restored.legacyFootprint);assert.equal(g.getState().grid[b.anchor+36],null);g.getState().researchCap=10;g.openPopup(b.anchor);g.upgradeSelected();assert.equal(restored.cells.length,2);assert.equal(restored.level,2);});

test('Disconnected moved buildings contribute nothing and resume on reconnection',()=>{const s=reset();add(8,7,'road');const plant=add(8,8,'coal');g.openPopup(plant.anchor);g.moveSelected();g.placeMoved(g.idx(20,20));assert.equal(plant.anchor,g.idx(20,20));g.calc();assert.equal(plant.netIncome,0);assert.equal(plant.netPollution,0);assert.equal(plant.workers,0);const capacity=s.powerCap;add(20,19,'road');g.calc();assert(s.powerCap>capacity);});
test('Loans keep total interest with half terms and allow full early repayment',()=>{const s=reset();s.money=0;assert(g.takeLoan(1000,1.5));assert.equal(s.loan.total,1060);assert.equal(s.loan.hourly,1060/(1.5*720));assert(!g.repayLoan());s.money=1060;assert(g.repayLoan());assert.equal(s.money,0);assert.equal(s.loan,null);});
test('Water and office improvements are available earlier',()=>{const s=reset();s.cityLevel=5;assert.equal(g.maxAllowedLevel('water'),5);s.cityLevel=g.DEF.office.unlock;assert(g.maxAllowedLevel('office')>=3);});


test('Merged parks sum mixed levels, preserve local influence, upgrade, move and reload in both orientations',()=>{
 for(const vertical of [false,true]){
  const s=reset();const rawPark=(x,z,level)=>{const b={type:'park',level,anchor:g.idx(x,z),w:3,h:3,rot:0,occ:0,fire:0,palette:0,cells:[]};for(let dz=0;dz<3;dz++)for(let dx=0;dx<3;dx++)b.cells.push(g.idx(x+dx,z+dz));b.cells.forEach(i=>s.grid[i]=b);return b;};
  const a=rawPark(8,8,5),b=rawPark(vertical?8:11,vertical?11:8,7);for(let x=8;x<14;x++)add(x,7,'road');for(let z=8;z<14;z++)add(7,z,'road');const home=add(6,9,'residential',1,12);g.calc();
  const before=g.localResidentialSatisfaction(home,[a,b,home],50),cash=s.money;
  g.openPopup(a.anchor);assert(g.parkFusionGroup());assert(g.mergeSelected());const park=s.grid[a.anchor];assert.equal(s.money,cash);assert.equal(park.cells.length,18);assert.equal(g.uniqueBuildings().filter(b=>b.type==='park').length,1);
  for(const k of ['happiness','upkeep','pollutionReduce'])assert.equal(g.buildingDef(park)[k][park.level],g.DEF.park[k][5]+g.DEF.park[k][7]);
  assert(Math.abs(g.localResidentialSatisfaction(home,[park,home],50)-before)<1e-8);
  assert(!g.parkFusionGroup());g.upgradeSelected();assert.equal(park.level,6);assert.equal(park.cells.length,18);assert.equal(g.buildingDef(park).upkeep[6],g.DEF.park.upkeep[6]+g.DEF.park.upkeep[8]);
  for(const part of g.capture(park)){const ex=Math.abs(Math.cos(part.ry))*part.sx/2+Math.abs(Math.sin(part.ry))*part.sz/2,ez=Math.abs(Math.sin(part.ry))*part.sx/2+Math.abs(Math.cos(part.ry))*part.sz/2;assert(Number.isFinite(part.y));assert(Math.abs(part.x)+ex<=park.w/2+.02);assert(Math.abs(part.z)+ez<=park.h/2+.02);}
  g.moveSelected();g.placeMoved(g.idx(20,20));assert.equal(park.anchor,g.idx(20,20));assert.equal(park.cells.length,18);g.calc();assert.equal(park.netIncome,0);assert.equal(park.netPollution,0);add(20,19,'road');g.calc();assert.equal(park.netPollution,-g.buildingDef(park).pollutionReduce[park.level]);
  const saved=JSON.parse(JSON.stringify(g.citySnapshot()));g.restoreCity(saved);const restored=g.getState().grid[park.anchor];assert.equal(restored.cells.length,18);assert.deepEqual(Array.from(restored.parkLevels),[5,7]);g.openPopup(restored.anchor);g.demolishSelected();assert(restored.cells.every(c=>!g.getState().grid[c]));
 }
});
test('Park fusion rejects partial shared edges and compact legacy parks',()=>{
 const s=reset();const a={type:'park',level:5,w:3,h:3,anchor:g.idx(8,8),fire:0},b={...a,anchor:g.idx(11,9)};s.grid[a.anchor]=a;s.grid[b.anchor]=b;g.openPopup(a.anchor);assert.equal(g.parkFusionGroup(),null);b.anchor=g.idx(11,8);s.grid[b.anchor]=b;a.w=2;assert.equal(g.parkFusionGroup(),null);
});
test('Road markings follow lane count and every lit-level intersection has visual signals',()=>{
 const s=reset();const road=add(10,10,'road');add(9,10,'road');add(11,10,'road');s.river[road.anchor]=true;
 for(let level=1;level<=8;level++){road.level=level;const parts=g.captureRoad(road.anchor),lines=parts.filter(p=>['#e0d4b4','#eee8d3'].includes(p.col));assert.equal(lines.length,(g.ROAD_LANES[level]-1)*3);}
 s.river[road.anchor]=false;add(10,9,'road');for(const level of [3,4,8]){road.level=level;const parts=g.captureRoad(road.anchor),signals=parts.filter(p=>p.col==='#263a43'&&p.sy===.133);assert.equal(signals.length,level>=4?2:0);if(level>=4)assert(g.roadLamp(road.anchor,level));assert(parts.some(p=>['#e0d4b4','#eee8d3'].includes(p.col)));}
});


test('Goods are proportional continuous supply, isolated by road networks and create freight traffic',()=>{
 const s=reset();s.manualRotation=0;for(let x=5;x<=17;x++)add(x,7,'road');const factory=add(5,8,'heavy_industry'),a=add(10,8,'commercial'),b=add(15,8,'office');factory.workers=g.DEF.heavy_industry.jobs[1];
 const network=()=>{const all=g.uniqueBuildings(),rc=g.roadComponents();g.computeGoods(all,rc.comp,1,1);return {all,rc};};
 let {all,rc}=network();assert.equal(factory.goodsOutput,g.DEF.heavy_industry.goods[1]);assert.equal(a.goodsCoverage,1);assert.equal(b.goodsCoverage,1);assert.equal(g.goodsFactor(a),1);assert(s.goodsDelivered<=s.goodsCap);const routes=g.getGoodsRoutes();assert(routes.length>=2);assert(routes.every(r=>r.path.every(i=>s.grid[i]?.type==='road')));g.computeTraffic(all,rc.comp);assert(g.getTrafficRoutes().some(r=>r.kind==='freight'));assert(s.grid[g.idx(8,7)].trafficLoad>0);
 const demand=s.goodsUse;factory.workers=g.DEF.heavy_industry.jobs[1]*demand/g.DEF.heavy_industry.goods[1]/2;network();assert(Math.abs(a.goodsCoverage-.5)<1e-8);assert(Math.abs(b.goodsCoverage-.5)<1e-8);assert(Math.abs(g.goodsFactor(a)-.85)<1e-8);const output=factory.goodsOutput;network();assert.equal(factory.goodsOutput,output);assert(Math.abs(s.goodsDelivered-output)<1e-8);
 g.clearBuilding(s.grid[g.idx(8,7)]);network();assert.equal(a.goodsCoverage,0);assert.equal(b.goodsCoverage,0);assert.equal(g.goodsFactor(a),.7);assert.equal(g.getGoodsRoutes().length,0);assert(factory.goodsOutput>0);
 add(8,7,'road');factory.workers=65;({all,rc}=network());g.computeGoods(all,rc.comp,0,1);assert.equal(factory.goodsOutput,0);g.computeGoods(all,rc.comp,1,0);assert.equal(factory.goodsOutput,0);factory.workers=0;network();assert.equal(factory.goodsOutput,0);
});
test('Actual industrial operation uses assigned workers and supplies; consumers lose revenue when freight disappears',()=>{
 const s=reset();s.manualRotation=0;for(let x=4;x<=19;x++)add(x,8,'road');const home=add(4,9,'residential',8,800);add(6,9,'water',5);add(7,9,'water',5);add(8,9,'coal',5);const factory=add(11,9,'heavy_industry'),shop=add(14,9,'commercial');g.calc();assert.equal(factory.workers,g.DEF.heavy_industry.jobs[1]);assert(factory.goodsOutput>0);assert.equal(shop.goodsCoverage,1);assert.equal(shop.incomeBreakdown.goods,1);assert.equal(factory.currentIncome,0);assert(factory.netPollution>0&&factory.netPollution<g.DEF.coal.pollution[1]);
 const parts=g.captureProduction([factory]);assert(parts.length>0);g.setSpeed(1);g.updateCars(1);assert.notDeepEqual(g.captureProduction([factory]),parts);g.setSpeed(0);
 g.openPopup(factory.anchor);g.moveSelected();g.placeMoved(g.idx(25,25));g.calc();assert.equal(factory.goodsOutput,0);assert.equal(factory.netIncome,0);assert.equal(factory.netPollution,0);assert.equal(shop.goodsCoverage,0);assert.equal(shop.incomeBreakdown.goods,.7);assert(Math.abs(shop.currentIncome-g.commercialRevenue(shop.incomeBreakdown.base,shop.workers,g.DEF.commercial.jobs[1],shop.incomeBreakdown.supply,shop.incomeBreakdown.environment)*.7)<1e-8);assert.equal(g.captureProduction([factory]).length,0);
});
test('Advanced construction and upgrades require free goods on their own network, basic buildings do not',()=>{
 const s=reset();for(let x=5;x<12;x++)add(x,7,'road');add(20,7,'road');const factory=add(5,8,'heavy_industry');factory.workers=65;const rc=g.roadComponents();g.computeGoods(g.uniqueBuildings(),rc.comp,1,1);assert(g.goodsCanPlace('hospital',1,[g.idx(10,8),g.idx(11,8)]));assert(!g.goodsCanPlace('hospital',1,[g.idx(20,8),g.idx(21,8)]));assert(g.goodsCanPlace('residential',1,[g.idx(20,8)]));assert.equal(g.goodsRequirement('commercial'),0);assert(g.goodsRequirement('commercial',4,3)>0);assert(g.goodsRequirement('office',3,2)>0);assert(!g.goodsCanPlace('office',3,[g.idx(20,8)],2));
 const office=add(20,8,'office',2);g.openPopup(office.anchor);const cash=s.money;g.upgradeSelected();assert.equal(office.level,2);assert.equal(s.money,cash);
});
test('Two matching heavy factories forming 2x2 merge with capacities, upkeep and upgrades preserved',()=>{
 const s=reset();s.manualRotation=0;for(let x=7;x<=13;x++)add(x,7,'road');const factories=[8,9].map(x=>add(x,8,'heavy_industry',3));g.openPopup(factories[0].anchor);s.cityLevel=2;assert(!g.industrialFusionGroup());s.cityLevel=3;factories[1].level=2;assert(!g.industrialFusionGroup());factories[1].level=3;assert(g.industrialFusionGroup());factories[0].palette=2;const oldCells=factories.flatMap(g.buildingCells),cash=s.money;assert(g.mergeSelected());const complex=g.uniqueBuildings().find(b=>b.type==='industrial_complex');assert(complex);assert.equal(complex.palette,2);assert.equal(complex.level,3);assert.equal(complex.cells.length,4);assert.equal(s.money,cash);assert.equal(oldCells.filter(c=>!s.grid[c]).length,0);
 for(const k of ['goods','jobs','income','pollution','upkeep','power','water'])assert.equal(g.buildingDef(complex)[k][3],2*g.DEF.heavy_industry[k][3]);assert.equal(g.buildingUpgradeCost(complex),2*g.upgradeCost('heavy_industry',3));s.cityLevel=8;g.upgradeSelected();assert.equal(complex.level,4);const save=JSON.parse(JSON.stringify(g.citySnapshot()));g.restoreCity(save);const loaded=g.getState().grid[complex.anchor];assert.equal(loaded.type,'industrial_complex');assert.equal(loaded.cells.length,4);assert.equal(loaded.level,4);
});
test('Industry tiers and geometry are distinct, bounded, and cleaner than thermal power; recycling relief increases 80 percent',()=>{
 reset();assert.equal(g.DEF.heavy_industry.unlock,2);assert.equal(g.DEF.light_industry.unlock,4);
 for(let l=1;l<=5;l++){const h=g.DEF.heavy_industry,q=g.DEF.light_industry;assert(h.pollution[l]<g.DEF.coal.pollution[l]);assert(q.goods[l]<h.goods[l]);assert(q.goods[l]/q.pollution[l]>h.goods[l]/h.pollution[l]);assert.equal(q.income[l],0);assert.equal(h.income[l],0);}
 for(const type of ['heavy_industry','light_industry','industrial_complex']){let previous='';for(let level=1;level<=5;level++)for(let rot=0;rot<4;rot++){const fp=g.footprint(type,rot,level),parts=g.capture({type,level,rot,palette:0});assert.equal(parts.some(p=>p.mesh==='sawtooth'),type!=='light_industry');for(const p of parts){assert(Number.isFinite(p.y));const ex=Math.abs(Math.cos(p.ry))*p.sx/2+Math.abs(Math.sin(p.ry))*p.sz/2,ez=Math.abs(Math.sin(p.ry))*p.sx/2+Math.abs(Math.cos(p.ry))*p.sz/2;assert(Math.abs(p.x)+ex<=fp.w/2+.02,`${type} ${level} x`);assert(Math.abs(p.z)+ez<=fp.h/2+.02,`${type} ${level} z`);}if(!rot){assert.notEqual(JSON.stringify(parts),previous);previous=JSON.stringify(parts);}}assert.notDeepEqual(g.buildingPalette({type,palette:0}),g.buildingPalette({type,palette:1}));}
 assert.equal(g.DEF.recycling.pollutionReduce[1],12.96);assert.equal(g.DEF.wastewater.pollutionReduce[1],7.2);
});
test('Recycling nuisance affects only residences within four grid blocks',()=>{
 const s=reset();add(8,7,'road');add(12,7,'road');const home=add(8,8,'residential',1,10),plant={type:'recycling',level:1,anchor:g.idx(12,8),w:1,h:1,cells:[g.idx(12,8)],fire:0};s.grid[plant.anchor]=plant;const base=g.localResidentialSatisfaction(home,[home],60);const near=g.localResidentialSatisfaction(home,[home,plant],60);assert(near<base);g.clearBuilding(plant);plant.anchor=g.idx(13,8);plant.cells=[plant.anchor];s.grid[plant.anchor]=plant;add(13,7,'road');assert.equal(g.localResidentialSatisfaction(home,[home,plant],60),base);
});


test('Guided tutorial waits for a road, two homes and a shop, and resumes after saving',()=>{
 const s=reset();s.cityLevel=1;g.renderCityGuide();assert(!g.guideRequirementMet());g.advanceGuide();assert.equal(s.tutorialStep,0);
 add(8,8,'road');g.advanceGuide();assert.equal(s.tutorialStep,1);add(8,9,'residential');assert(!g.guideRequirementMet());add(8,7,'residential');g.advanceGuide();assert.equal(s.tutorialStep,2);
 g.restoreCity(JSON.parse(JSON.stringify(g.citySnapshot())));assert.equal(g.getState().tutorialStep,2);assert(!g.guideRequirementMet());add(9,8,'road');add(9,9,'commercial');g.advanceGuide();assert.equal(g.getState().tutorialStep,3);
 g.getState().tutorialDone=true;g.getState().cityLevel=2;assert.equal(g.currentUnlockAdvice()[0],'heavy_industry');g.advanceGuide();assert.equal(g.currentUnlockAdvice(),undefined);
});
test('Maximum upgrade pays successive levels and stops on budget, city cap or blocked expansion',()=>{
 let s=reset();add(8,7,'road');let b=add(8,8,'residential');const c1=g.buildingUpgradeCost(b);b.level=2;const c2=g.buildingUpgradeCost(b);b.level=1;s.money=c1+c2;g.openPopup(b.anchor);g.upgradeToMaximum();assert.equal(b.level,3);assert.equal(s.money,0);
 s=reset();s.cityLevel=1;add(8,7,'road');b=add(8,8,'residential');g.openPopup(b.anchor);const cash=s.money;g.upgradeToMaximum();assert.equal(b.level,g.maxAllowedLevel('residential'));assert(s.money<=cash);
 s=reset();add(8,7,'road');b=add(8,8,'park',4);s.landUnlocked.fill(false);b.cells.forEach(c=>s.landUnlocked[c]=true);g.openPopup(b.anchor);const funds=s.money;g.upgradeToMaximum();assert.equal(b.level,4);assert.equal(s.money,funds);
});
test('Road quote includes bridge premiums, skips roads, stops at obstacles, and moving leaves no selection',()=>{
 const s=reset();add(8,8,'road');s.river[g.idx(9,8)]=true;const cells=[g.idx(8,8),g.idx(9,8),g.idx(10,8)];const q=g.roadConstructionQuote(cells);assert.equal(q.cost,g.buildPrice('road')*3);s.roadDragCells=cells;const cash=s.money;g.buildRoadDrag();assert.equal(cash-s.money,q.cost);
 const b=add(10,9,'residential');g.openPopup(b.anchor);g.moveSelected();g.placeMoved(g.idx(15,15));assert.equal(b.anchor,g.idx(15,15));assert.equal(s.selected,null);assert(g.buildingStats(b).some(([label])=>label==='Consumo eléctrico'));
});
test('News alternates queued facts with satire and never repeats after save and reload',()=>{
 const s=reset();doc.querySelector('#cityAccess').hidden=true;doc.querySelector('#startScreen').hidden=true;g.addEvent('Hito A');g.addEvent('Hito B');assert.equal(s.newsSeen[0],'Hito A');g.presentNextNews();assert(s.newsSeen[1]!==s.newsSeen[0]);g.presentNextNews();assert.equal(s.newsSeen[2],'Hito B');g.addEvent('Hito A');assert(!s.newsQueue.some(n=>n.text==='Hito A'));
 const seen=[...s.newsSeen];g.restoreCity(JSON.parse(JSON.stringify(g.citySnapshot())));g.addEvent('Hito A');assert.equal(g.getState().newsSeen.filter(t=>t==='Hito A').length,1);assert(seen.every(t=>g.getState().newsSeen.includes(t)));
});
test('Monuments have three bounded models, cost 25000 and provide one wellbeing point',()=>{
 const s=reset();s.cityLevel=5;assert(g.buildingLocked('monument'));s.cityLevel=6;assert(!g.buildingLocked('monument'));assert.equal(g.buildPrice('monument'),25000);assert.equal(g.DEF.monument.happiness[1],1);
 add(8,8,'road');const h=add(8,9,'residential',1,12);add(9,8,'road');const cash=s.money,m=add(9,9,'monument');assert.equal(cash-s.money,25000);assert.equal(m.cells.length,1);g.calc();const base=g.localResidentialSatisfaction(h,[h],50),boost=g.localResidentialSatisfaction(h,[h,m],50)-base;assert(Math.abs(boost-g.DEF.monument.happiness[1]*1.25*(1-1/5.2))<1e-8);assert.equal(m.netPollution,0);assert.equal(m.netIncome,0);
 const counts=[];for(let palette=0;palette<3;palette++){const parts=g.capture({type:'monument',level:1,palette,rot:0});counts.push(parts.length);for(const part of parts){assert(Math.abs(part.x)+part.sx/2<=.5);assert(Math.abs(part.z)+part.sz/2<=.5);}}assert.equal(new Set(counts).size,3);
 const save=g.citySnapshot();g.restoreCity(JSON.parse(JSON.stringify(save)));assert.equal(g.getState().grid[m.anchor].palette,m.palette);
});


test('Demand bars use production as their maximum, including zero capacity',()=>{
 const s=reset();s.researchCap=4;s.researchUse=1;s.goodsCap=100;s.goodsUse=25;s.goodsDelivered=25;g.renderResearchAndLoan();assert.equal(nodes.get('#researchBar').style.width,'25%');assert.equal(nodes.get('#goodsBar').style.width,'25%');assert.equal(nodes.get('#researchText').textContent,'1.00 / 4.00');s.researchCap=0;s.goodsCap=0;g.renderResearchAndLoan();assert.equal(nodes.get('#researchBar').style.width,'100%');s.researchUse=s.goodsUse=0;g.renderResearchAndLoan();assert.equal(nodes.get('#researchBar').style.width,'0%');assert.equal(nodes.get('#goodsBar').style.width,'0%');
});
test('Transit relieves nearby roads more than remote ones and routing takes an alternative',()=>{
 const s=reset();for(let x=3;x<=17;x++)add(x,7,'road');const hub=add(7,8,'transit');hub.serviceEfficiency=1;const near=s.grid[g.idx(7,7)],far=s.grid[g.idx(17,7)];assert(g.transitRoadRelief(near,[hub])>0);assert.equal(g.transitRoadRelief(far,[hub]),0);hub.serviceEfficiency=0;assert.equal(g.transitRoadRelief(near,[hub]),0);assert.equal(g.ROAD_LANES[8],6);assert.equal(g.roadLaneDividers(8,.8).length,5);
});
test('Industry emissions match its actual output; employment is reduced and industry earns no revenue',()=>{
 const s=reset();s.debug=true;add(8,7,'road');const f=add(8,8,'heavy_industry');f.industryEfficiency=.5;assert.equal(g.buildingEmissions(f),g.DEF.heavy_industry.pollution[1]*.5);assert.equal(g.DEF.heavy_industry.jobs[1],13);assert.equal(g.DEF.light_industry.jobs[1],10);assert.equal(g.DEF.research.research[1],1.4);assert.equal(g.DEF.school.jobs[1],24);for(const type of ['heavy_industry','light_industry','industrial_complex'])for(let l=1;l<=5;l++)assert.equal(g.DEF[type].income[l],0);
 g.openPopup(f.anchor);g.moveSelected();g.placeMoved(g.idx(20,20));assert.equal(g.buildingEmissions(f),0);
});
test('Debug builds disconnected structures, while a merged residence needs only one road contact',()=>{
 const s=reset();s.debug=true;for(const [x,z] of [[12,12],[13,12],[12,13],[13,13]])add(x,z,'residential',4,25);g.openPopup(g.idx(12,12));assert(g.mergeSelected());const house=s.grid[g.idx(12,12)];g.calc();assert(!g.operational(house.anchor));assert.equal(house.netIncome,0);assert.equal(s.pop,0);add(11,12,'road');g.calc();assert(g.operational(house.anchor));assert.equal(s.pop,100);assert(s.powerUse>0);s.debug=false;s.cityLevel=2;assert.equal(g.maxAllowedLevel('park'),2);
});
test('Extinguished fires always remove exactly one level, regardless of protection',()=>{
 const s=reset();s.debug=false;for(let x=8;x<=12;x++)add(x,7,'road');const b=add(8,8,'commercial',3);add(10,8,'fire',5);b.fire=.001;const random=ctx.Math.random;ctx.Math.random=()=>.999;try{g.advance(.01);}finally{ctx.Math.random=random;}assert.equal(b.level,2);assert.equal(b.fire,0);
});
test('News stays unread under start screen and immediately becomes visible when play starts',()=>{
 const s=reset();doc.querySelector('#cityAccess').hidden=true;doc.querySelector('#startScreen').hidden=false;g.addEvent('Primera noticia');assert.equal(s.newsSeen.length,0);g.cityNews([]);assert.equal(s.newsSeen.length,0);doc.querySelector('#startScreen').hidden=true;g.cityNews([]);assert.equal(s.newsSeen[0],'Primera noticia');assert(s.newsActive);
});
