const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('public/ciudad-viva/index.html','utf8');
const nodes=new Map();
function node(){return{style:{setProperty(){}},closest(){return this},dataset:{},children:[],textContent:'',innerHTML:'',classList:{add(){},remove(){},toggle(){},contains(){return false}},addEventListener(){},prepend(x){this.children.unshift(x);if(this.children.length>14)this.children.pop()},appendChild(x){this.children.push(x)},remove(){},setAttribute(){},getBoundingClientRect(){return{left:0,top:0,width:1100,height:720}},offsetWidth:330,offsetHeight:320,clientWidth:1100,clientHeight:720,setPointerCapture(){}};}
const gl=new Proxy({getShaderParameter(){return true},getProgramParameter(){return true},getAttribLocation(){return 0},getUniformLocation(){return{}},getShaderInfoLog(){return''},getProgramInfoLog(){return''}}, {get:(o,k)=>o[k]||(()=>({}))});
const doc={body:node(),querySelector(sel){if(!nodes.has(sel))nodes.set(sel,node());return nodes.get(sel)},querySelectorAll(){return[]},createElement:node,addEventListener(){}};
doc.querySelector('#glCanvas').getContext=()=>gl;
const ctx={document:doc,window:{addEventListener(){}},performance:{now:()=>1000},requestAnimationFrame(){},setTimeout(){},setInterval(){},fetch:()=>new Promise(()=>{}),AbortSignal,clearTimeout(){},devicePixelRatio:1,console,Math,Float32Array,Uint16Array};
vm.createContext(ctx);
let js=html.match(/<script>([\s\S]*?)<\/script>/)[1];
js=js.replace(/\}\)\(\);\s*$/, `Object.assign(thisTest,{upgradeSpace,renderEmergency,windowLight,hasCrosswalk,roadColor,roadDragQuote,metricAvailable,layerValue,localServices,cityParticles,getServiceCars:()=>serviceCars,fusionGroup,mergeSelected,renameCity,rotatePlacement,generateRiver,buildingDef,buildingUpgradeCost,canPlace,currentSun,drawRoadTile,renderCityGuide,takeLoan,loanLimit,loanHourly,loanTerms,unlockTechnology,buildingLocked,buildPrice,taxDiscomfort,spreadFires,fireProtection,trafficSpeedFactor,simulationRate,serviceEfficiency,citySnapshot,restoreCity,setDebug,canAfford,changeMoney,ensureLevel,maxAllowedLevel,commercialRevenue,apportion,buildingStats,renderUI,buildRoadDrag,demolishSelected,getState:()=>S,setState:s=>S=s,newState,DEF,LEVELS,UP_MULT,idx,coord,footprint,build,calc,advance,uniqueBuildings,placementRotation,buildingCells,openPopup,moveSelected,placeMoved,cancelAction,showLandPopup,buySelectedLand,upgradeSelected,upgradeCost,drawBuilding,thumbSVG,power,STAR_FIELD,render3D,updateCars,getCars:()=>cars,setSpeed:n=>runningSpeed=n,resetCars:()=>cars=[],captureRoad:(i)=>{captureParts=[];const c=coord(i),w=worldFromCell(c.x,c.z);drawRoadTile(i,S.grid[i],w);const p=captureParts;captureParts=null;return p;},geometryFor,smogAmount,capture:b=>{captureParts=[];const fp=footprint(b.type,b.rot||0,b.level);drawBuilding({...b,w:fp.w,h:fp.h,anchor:0},-(fp.w-1)/2,-(fp.h-1)/2);const p=captureParts;captureParts=null;return p;}});})();`);
ctx.thisTest={};vm.runInContext(js,ctx);const g=ctx.thisTest;
function reset(){g.setState(g.newState());const s=g.getState();s.landUnlocked.fill(true);s.river.fill(false);s.money=1e8;s.cityLevel=8;return s;}
function add(x,z,t,l=1,occ=0){const s=g.getState(),i=g.idx(x,z);g.build(i,t);const b=s.grid[i];assert(b&&b.type===t,`build ${t} ${x},${z}`);b.level=l;b.occ=occ;return b;}
const results=[];function test(n,f){f();results.push(n);console.log('PASS',n)}

test('Cloud save round-trip preserves shared footprints, upgrades, occupation and resources',()=>{const s=reset();add(8,8,'road');add(9,8,'road');add(10,8,'road');const park=add(8,9,'park',3);const home=add(10,9,'residential',4,65.7);s.day=200;s.money=43210;s.debug=true;s.unlockAt.school=42;const snapshot=g.citySnapshot();g.restoreCity(JSON.parse(JSON.stringify(snapshot)));const restored=g.getState();assert.equal(restored.money,43210);assert.equal(restored.day,200);assert.equal(restored.debug,true);assert.equal(restored.unlockAt.school,42);assert.equal(restored.grid[home.anchor].occ,65.7);assert.equal(restored.grid[park.anchor].level,3);assert.strictEqual(restored.grid[park.anchor],restored.grid[park.anchor+1]);assert.equal(g.uniqueBuildings().length,5);assert.deepEqual(JSON.parse(JSON.stringify(g.citySnapshot())),JSON.parse(JSON.stringify(snapshot)));});
test('Final local services retain disease, crime and water penalties; fire coverage is zero without firefighters',()=>{
 const s=reset();s.day=100;s.unlockAt={clinic:0,school:0,police:0,fire:0};for(let x=4;x<=12;x++)add(x,8,'road',5);const h=add(5,9,'residential',8,300);add(6,9,'clinic',3);add(7,9,'police',2);add(8,9,'water',4);const power=add(10,9,'coal',4);g.calc();const health=s.health,security=s.security;assert.equal(s.fireSafety,0);assert.equal(g.fireProtection(h),0);s.diseaseDays=10;s.crimeDays=10;g.calc();assert(Math.abs(s.health-(health-8))<.001);assert(Math.abs(s.security-(security-6))<.001);s.diseaseDays=s.crimeDays=0;const services=g.uniqueBuildings();const full=g.localServices([h],services,0,1,1).health,dry=g.localServices([h],services,0,1,0).health;assert(dry<full-20);s.grid[power.anchor]=null;g.calc();assert(g.localServices([h],g.uniqueBuildings(),0,.2,1).health<g.localServices([h],g.uniqueBuildings(),0,1,1).health);assert(s.waterCap<g.DEF.water.waterCap[4]);assert(g.uniqueBuildings().find(b=>b.type==='clinic').serviceEfficiency<1);
});
test('Crime lowers satisfaction in underserved homes; service saturation remains effective',()=>{
 const s=reset();s.day=100;s.unlockAt={police:0};for(let x=4;x<10;x++)add(x,8,'road');const h=add(5,9,'residential',4,80);add(6,9,'water',3);add(7,9,'coal',3);g.calc();const baseline=h.localSatisfaction;s.crimeDays=10;g.calc();assert(h.localSatisfaction<baseline-9);s.crimeDays=0;add(9,9,'school');const all=g.uniqueBuildings();h.occ=100;const small=g.localServices([h],all,0).education;h.occ=700;assert(g.localServices([h],all,0).education<small);
});
test('Fire spreads only to immediately adjacent buildings, with less spread under fire cover',()=>{
 const s=reset();for(let x=3;x<12;x++)add(x,8,'road');const source=add(4,9,'commercial'),near=add(5,9,'residential'),far=add(8,9,'commercial');source.fire=5;s.fireSafety=0;near.localServices={fire:0};assert.equal(g.spreadFires(1,()=>.02),1);assert(near.fire>0);assert.equal(far.fire,0);near.fire=0;near.localServices.fire=95;s.fireSafety=95;assert.equal(g.spreadFires(1,()=>.02),0);
});
test('Unused roads do not dilute weighted congestion; full congestion nearly stops cars',()=>{
 const s=reset();for(let x=4;x<13;x++)add(x,8,'road');add(4,9,'residential',7,400);add(12,9,'commercial',5);g.calc();g.calc();const original=s.avgTraffic;assert(original>0);for(let x=0;x<20;x++)add(x,0,'road');g.calc();assert(Math.abs(s.avgTraffic-original)<.0001);assert(g.trafficSpeedFactor(100)<.02);assert(g.trafficSpeedFactor(30)>.2);
});
test('Higher taxes directly reduce satisfaction convexly; construction and upgrades scale with city size',()=>{
 const s=reset();s.cityLevel=1;const initial=g.buildPrice('residential'),upgrade=g.upgradeCost('commercial',1);s.cityLevel=8;assert(g.buildPrice('residential')>initial*7);assert(g.upgradeCost('commercial',1)>upgrade*7);assert.equal(g.taxDiscomfort(10),0);assert(g.taxDiscomfort(20)-g.taxDiscomfort(15)>g.taxDiscomfort(15)-g.taxDiscomfort(10));s.cityLevel=1;add(8,8,'road');add(8,7,'water');const h=add(8,9,'residential',1,18);s.tax=10;g.calc();const happy=s.happiness;s.tax=20;g.calc();assert(s.happiness<happy-30);
});
test('Emergency loan respects bankruptcy, term, city cap and single outstanding debt; installments amortize exactly',()=>{
 const s=reset();s.cityLevel=3;s.money=1;assert(!g.takeLoan(10000,3));s.money=0;assert(!g.takeLoan(g.loanLimit()+1,3));assert(!g.takeLoan(10000,4));assert(g.takeLoan(10000,3));assert(!g.takeLoan(10,3));const payment=g.loanHourly();assert.equal(s.money,10000);assert.equal(s.loan.total,10600);g.advance(1);assert(Math.abs(s.loan.remaining-(10600-payment))<.0001);assert(Math.abs(s.money-(10000-payment))<.0001);g.advance(3*30*24);assert.equal(s.loan,null);assert(Math.abs(s.money+600)<.0001);assert(g.loanTerms(10000,12).interest>g.loanTerms(10000,3).interest);
});
test('Research requires a powered staffed center and city level, spends points once and survives save/load with loans',()=>{
 const s=reset();s.cityLevel=4;for(let x=4;x<12;x++)add(x,8,'road');add(4,9,'residential',5,100);add(9,9,'coal',3);add(7,9,'water',3);add(8,9,'research');g.calc();assert(s.researchRate>0);g.advance(2);assert(s.researchPoints>0);s.researchPoints=1000;assert(!g.unlockTechnology('solar'));s.cityLevel=5;assert(g.buildingLocked('solar'));assert(g.unlockTechnology('solar'));assert.equal(s.researchPoints,920);assert(!g.unlockTechnology('solar'));assert.equal(g.maxAllowedLevel('solar'),2);s.money=0;assert(g.takeLoan(1000,6));const snapshot=g.citySnapshot();g.restoreCity(JSON.parse(JSON.stringify(snapshot)));assert.deepEqual(JSON.parse(JSON.stringify(g.citySnapshot())),JSON.parse(JSON.stringify(snapshot)));
});
test('Normal time is halved, debug permits x10 and switching back caps speed',()=>{const s=reset();g.setSpeed(1);assert.equal(g.simulationRate(),.175);g.setDebug(true);g.setSpeed(10);assert.equal(g.simulationRate(),1.75);g.setDebug(false);assert.equal(g.simulationRate(),.175);g.setSpeed(0);});
test('Starter budget still reaches first promotion with the revised supply and traffic calculation',()=>{const s=g.newState();s.river.fill(false);g.setState(s);for(let x=16;x<=20;x++)add(x,12,'road');add(18,11,'water');add(19,11,'commercial');add(16,11,'coal');for(const [x,z] of [[16,13],[17,13],[18,13],[19,13],[20,13],[20,11]])add(x,z,'residential');assert(s.money>=0);for(let n=0;n<1000&&s.cityLevel<2;n++)g.advance(.5);assert(s.cityLevel>=2,`stalled ${s.pop}`);assert(s.money>0);});
test('Fusion of equal N4+ homes preserves capacity, occupancy and upkeep, upgrades and reloads as one unit',()=>{for(const level of [4,6,8]){const s=reset();for(let x=8;x<=11;x++){add(x,7,'road');add(x,10,'road');}const homes=[[9,8],[10,8],[9,9],[10,9]].map(([x,z])=>add(x,z,'residential',level,60));g.openPopup(homes[0].anchor);assert(g.fusionGroup());assert(g.mergeSelected());const b=s.grid[homes[0].anchor];assert.equal(b.type,'residential_block');assert.equal(b.level,4);assert.equal(b.occ,240);assert.equal(g.buildingDef(b).cap[4],g.DEF.residential.cap[level]*4);assert.equal(g.buildingDef(b).upkeep[4],g.DEF.residential.upkeep[level]*4);assert.equal(g.uniqueBuildings().filter(b=>b.type==='residential_block').length,1);g.upgradeSelected();assert.equal(b.level,5);const saved=g.citySnapshot();g.restoreCity(JSON.parse(JSON.stringify(saved)));assert.equal(g.getState().grid[b.anchor].baseLevel,level);assert.equal(g.getState().grid[b.anchor].cells.length,4);}});
test('Fusion rejects mismatched levels and non-square groups',()=>{const s=reset();for(let x=8;x<13;x++)add(x,7,'road');const a=add(8,8,'residential',4);add(9,8,'residential',5);add(10,8,'residential',4);add(11,8,'residential',4);g.openPopup(a.anchor);assert.equal(g.fusionGroup(),null);assert(!g.mergeSelected());});
test('Park expansion is atomic, requires 3x3 land and preserves money and cells when blocked',()=>{const s=reset();add(8,7,'road');const park=add(8,8,'park',4);s.landUnlocked[g.idx(10,10)]=false;for(let z=7;z<=10;z++)s.landUnlocked[g.idx(7,z)]=false;g.openPopup(park.anchor);const cash=s.money;g.upgradeSelected();assert.equal(park.level,4);assert.equal(park.cells.length,4);assert.equal(s.money,cash);s.landUnlocked[g.idx(10,10)]=true;g.upgradeSelected();assert.equal(park.level,5);assert.equal(park.cells.length,9);assert(s.money<cash);assert.strictEqual(s.grid[g.idx(10,10)],park);});
test('Rectangular buildings rotate before placement; legacy compact buildings reload without overlap',()=>{for(const type of ['coal','hospital','nuclear','solar']){const s=reset();s.debug=true;add(8,7,'road');s.tool=type;s.manualRotation=0;g.rotatePlacement();assert.equal(s.manualRotation,1);const b=add(8,8,type);assert.equal(b.rot,1);assert.equal(b.cells.length,2);}const s=reset();const state=g.citySnapshot();state.format=1;state.buildings=[{type:'coal',level:1,anchor:200,rot:0,occ:0,palette:0,fire:0},{type:'commercial',level:1,anchor:201,rot:0,occ:0,palette:0,fire:0}];g.restoreCity(state);assert.equal(g.getState().grid[200].cells.length,1);assert.equal(g.getState().grid[201].type,'commercial');});
test('Every new map contains a connected winding river; bridges cost twice a road and twice to upgrade',()=>{for(let seed=0;seed<30;seed++){const river=g.generateRiver(seed);assert(river.some(Boolean));const cells=river.flatMap((v,i)=>v?[i]:[]),seen=new Set([cells[0]]),queue=[cells[0]];while(queue.length){const i=queue.pop(),x=i%36;for(const n of [i-36,i+36,...(x>0?[i-1]:[]),...(x<35?[i+1]:[])])if(n>=0&&n<864&&river[n]&&!seen.has(n)){seen.add(n);queue.push(n);}}assert.equal(seen.size,cells.length);}const s=reset();s.river[g.idx(8,8)]=true;const cash=s.money,b=add(8,8,'road');assert.equal(cash-s.money,g.buildPrice('road')*2);assert.equal(g.buildingUpgradeCost(b),g.upgradeCost('road',1)*2);});
test('Land purchase requires Urbanizar; rename costs 1000; fixed day and layers do not stop simulation',()=>{const s=reset();s.landUnlocked[0]=false;s.tool='inspect';g.showLandPopup(0);g.buySelectedLand();assert(!s.landUnlocked[0]);s.tool='land';g.showLandPopup(0);g.buySelectedLand();assert(s.landUnlocked[0]);const cash=s.money;assert(g.renameCity('Nueva Toledo'));assert.equal(s.money,cash-1000);s.day=0;s.dayNight=false;assert.equal(g.currentSun().hour,12);s.dayNight=true;s.layer='traffic';assert.equal(g.currentSun().hour,12);s.layer='none';assert.equal(g.currentSun().hour,0);const day=s.day;g.advance(.1);assert(s.day>day);});
test('New geometry and every rectangular rotation remain within their parcels',()=>{for(const type of ['residential_block','park','coal','hospital','nuclear','recycling','university','transit','research'])for(const level of type==='residential_block'?[4,8]:type==='park'?[4,5]:[1,g.DEF[type].max])for(const rot of [0,1]){const fp=g.footprint(type,rot,level),parts=g.capture({type,level,rot,palette:0});for(const p of parts){const ex=Math.abs(Math.cos(p.ry))*p.sx/2+Math.abs(Math.sin(p.ry))*p.sz/2,ez=Math.abs(Math.sin(p.ry))*p.sx/2+Math.abs(Math.cos(p.ry))*p.sz/2;assert(Math.abs(p.x)+ex<=fp.w/2+.02,`${type} N${level} rot${rot} X`);assert(Math.abs(p.z)+ez<=fp.h/2+.02,`${type} N${level} rot${rot} Z`);}}});

test('Fusion requires all four homes at N4, including debug; old low-level fused saves remain compatible',()=>{const s=reset();s.cityLevel=4;for(let x=10;x<12;x++){add(x,9,'road');add(x,12,'road');}for(let x=10;x<12;x++)for(let z=10;z<12;z++)add(x,z,'residential',1,5);g.openPopup(g.idx(10,10));assert.equal(nodes.get('#mergeBtn').disabled,true);assert(!g.mergeSelected());s.debug=true;assert.equal(g.fusionGroup(),null);for(const b of g.uniqueBuildings())if(b.type==='residential')b.level=4;assert(g.mergeSelected());const snapshot=g.citySnapshot();snapshot.buildings.find(b=>b.type==='residential_block').baseLevel=1;g.restoreCity(snapshot);assert.equal(g.buildingDef(g.getState().grid[g.idx(10,10)]).cap[4],4*g.DEF.residential.cap[1]);});
test('Asphalt is above paving at all upgraded road levels; tower geometry is bounded and economical',()=>{const s=reset(),b=add(10,10,'road');for(let level=2;level<=8;level++){b.level=level;const parts=g.captureRoad(b.anchor),paving=parts.filter(p=>p.col==='#b4b7a9'),asphalt=parts.filter(p=>p.col===g.roadColor(0));assert(paving.length&&asphalt.length);assert(Math.min(...asphalt.map(p=>p.y+p.sy/2))>Math.max(...paving.map(p=>p.y+p.sy/2)));}assert(g.geometryFor('cooling').indices.length/3<=64);s.layer='none';s.pollution=20;assert.equal(g.smogAmount(),0);s.pollution=70;assert(g.smogAmount()>0);s.layer='traffic';assert.equal(g.smogAmount(),0);g.render3D();});

test('Park expands northwest when east and south are unavailable',()=>{const s=reset();add(9,10,'road');const b=add(8,8,'park',4);for(let z=7;z<=10;z++)s.landUnlocked[g.idx(10,z)]=false;for(let x=7;x<=10;x++)s.landUnlocked[g.idx(x,10)]=false;g.openPopup(b.anchor);g.upgradeSelected();assert.equal(b.level,5);assert.equal(b.anchor,g.idx(7,7));assert.equal(b.cells.length,9);assert.strictEqual(s.grid[g.idx(8,8)],b);});
test('Wastewater needs an orthogonal river neighbor for placement and relocation',()=>{const s=reset();add(8,7,'road');s.river[g.idx(9,9)]=true;assert(!g.canPlace(g.idx(8,8),'wastewater'));s.river[g.idx(9,8)]=true;const b=add(8,8,'wastewater');add(12,7,'road');g.openPopup(b.anchor);g.moveSelected();g.placeMoved(g.idx(12,8));assert.equal(b.anchor,g.idx(8,8));s.river[g.idx(13,8)]=true;g.placeMoved(g.idx(12,8));assert.equal(b.anchor,g.idx(12,8));});
test('Old 30x24 cities migrate to 36x24 without changing coordinates or compact campus buildings',()=>{reset();const state=g.citySnapshot();state.format=2;state.width=30;state.landUnlocked=Array(720).fill(true);state.river=Array(720).fill(false);state.river[29]=true;state.buildings=[{type:'university',level:1,w:1,h:1,anchor:200,rot:0,occ:0,fire:0,palette:0}];g.restoreCity(state);const s=g.getState(),anchor=g.idx(20,6);assert.equal(s.grid.length,864);assert.equal(s.grid[anchor].type,'university');assert.equal(s.grid[anchor].cells.length,1);assert(s.river[29]);assert(!s.landUnlocked[30]);assert.equal(g.citySnapshot().format,3);});
test('Bankruptcy immediately pauses, rejects insufficient rescue and preserves Game Over on reload',()=>{const s=reset();s.money=-501;g.setSpeed(1);g.renderEmergency();assert.equal(g.simulationRate(),0);assert.equal(nodes.get('#emergencyScreen').hidden,false);const day=s.day;g.advance(1);assert.equal(s.day,day);assert(!g.takeLoan(500,3));assert(g.takeLoan(1000,3));assert.equal(nodes.get('#emergencyScreen').hidden,true);s.money=-10;s.gameOver=true;const snapshot=g.citySnapshot();g.restoreCity(snapshot);assert(g.getState().gameOver);assert.equal(nodes.get('#restartCity').hidden,false);});
test('City promotion requires happiness as well as population and existing services',()=>{const s=reset();s.pop=80;s.happiness=44;assert(!g.LEVELS[1].req(s));s.happiness=45;assert(g.LEVELS[1].req(s));s.pop=240;s.happiness=60;s.education=34;assert(!g.LEVELS[2].req(s));s.education=35;assert(g.LEVELS[2].req(s));});
